<aside class="chat-side hide-chat display" id="chatSide">
	<div class="chat-frame">
		<div class="chatted-lib" >
			<a id="chattedLib" href="" style="display:none">
				<div><img id="chattedImg" src="" alt=""></div>
				<span id="chattedTitle" ></span>
			</a>
		</div>
		<div class="chat" id="chat" style="display:none">
			<div class="chat-c" id="chatC">
				<div id="moreChat" style="margin-top: 1px;"></div>
			</div>
			<div class="chat__footer">
				<div contenteditable class="intxt txt-area chat__txtarea" id="chatMsg"></div>
				<div class="send-chat" id="sendChatMsgBtn"></div>
			</div>
		</div>
	</div>
	<div class="trans" id="trans2"></div>
</aside>