<?php
if (!isset($_SESSION['user_id'])){
	header('location: ../index.php');
	exit();
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link
			rel="icon"
			type="image/png"
			sizes="32x32"
			href="<?php echo $styleImg. 'logo32x32.png'?>"
	/>
	<title>
		<?php 
		if (isset($rootPage)){
			echo 'Lib';
		}elseif(isset($lib)){
			echo  getLibTitle($conn,$_GET['id']) . ' | Lib';
		}
		?></title>
	<script src="<?php echo $js . 'header.js' ?>"></script>
	<link rel="stylesheet" href="<?php echo $css . 'reset.css' ?>"/>
	<link rel="stylesheet" href="<?php echo $css . 'main.css' ?>"/>